In [1]:
import pandas as pd

In [2]:
scraper = pd.read_html("https://en.wikipedia.org/wiki/Premier_League_records_and_statistics")

In [3]:
scraper

[   Rank           Player  Games    Position First season Last season
 0     1     Gareth Barry    653  Midfielder      1997–98     2017–18
 1     2       Ryan Giggs    632  Midfielder      1992–93     2013–14
 2     3    Frank Lampard    609  Midfielder      1995–96     2014–15
 3     4     James Milner    607  Midfielder      2002–03     2022–23
 4     5      David James    572  Goalkeeper      1992–93     2009–10
 5     6       Gary Speed    535  Midfielder      1992–93     2007–08
 6     7     Emile Heskey    516     Forward      1994–95     2011–12
 7     8   Mark Schwarzer    514  Goalkeeper      1996–97     2014–15
 8     9  Jamie Carragher    508    Defender      1996–97     2012–13
 9    10     Phil Neville    505    Defender      1994–95     2012–13,
    Rank         Player  Goals  Games  Ratio    Position First goal Last goal
 0     1   Alan Shearer    260    441   0.59     Forward    1992–93   2005–06
 1     2   Wayne Rooney    208    491   0.42     Forward    2002–03   2017–18
 2     3     Harry Kane    201    308   0.65     Forward    2013–14   2022–23
 3     4      Andy Cole    187    414   0.45     Forward    1993–94   2006–07
 4     5  Sergio Agüero    184    284   0.65     Forward    2011–12   2020–21
 5     6  Frank Lampard    177    609   0.29  Midfielder    1997–98   2014–15
 6     7  Thierry Henry    175    258   0.68     Forward  1999–2000   2011–12
 7     8  Robbie Fowler    163    379   0.43     Forward    1993–94   2006–07
 8     9  Jermain Defoe    162    496   0.33     Forward    2001–02   2017–18
 9    10   Michael Owen    150    326   0.46     Forward    1996–97   2012–13,
    Rank           Player  Scored  Taken  Ratio Playing position
 0     1     Alan Shearer      56     67   0.84          Forward
 1     2    Frank Lampard      43     50   0.86       Midfielder
 2     3   Steven Gerrard      32     41   0.78       Midfielder
 3     4       Harry Kane      30     34   0.88          Forward
 4     5       Mark Noble      28     33   0.85       Midfielder
 5     6    Sergio Aguero      27     33   0.82          Forward
 6     7      Jamie Vardy      26     31   0.84          Forward
 7     8  Matt Le Tissier      25     26   0.96       Midfielder
 8    10    Thierry Henry      23     25   0.92          Forward
 9    10     Wayne Rooney      23     34   0.68          Forward,
     Rank                 Player  Goals  Games  Ratio Playing position
 0      1          David Beckham     18    265  0.068       Midfielder
 1      2      James Ward-Prowse     17    330  0.052       Midfielder
 2      3      Cristiano Ronaldo     12    236  0.051          Forward
 3      3        Gianfranco Zola     12    229  0.052          Forward
 4      3          Thierry Henry     12    258  0.047          Forward
 5      6         Laurent Robert     11    150  0.073          Forward
 6      6      Sebastian Larsson     11    282  0.039       Midfielder
 7      8              Ian Harte     10    237  0.042         Defender
 8      8  Morten Gamst Pedersen     10    260  0.038       Midfielder
 9     10         Jamie Redknapp      9    295  0.031       Midfielder
 10    10        Nolberto Solano      9    302  0.030       Midfielder
 11    10          Frank Lampard      9    609  0.015       Midfielder,
    Rank           Player  Assists  Games  Ratio    Position First assist  \
 0     1       Ryan Giggs      162    632   0.26  Midfielder      1992–93
 1     2    Cesc Fàbregas      111    350   0.32  Midfielder      2004–05
 2     3     Wayne Rooney      103    491   0.21     Forward      2002–03
 3     4    Frank Lampard      102    609   0.17  Midfielder      1997–98
 4     5  Kevin De Bruyne       98    234   0.42  Midfielder      2013–14
 5     6  Dennis Bergkamp       94    315   0.30     Forward      1995–96
 6     7      David Silva       93    309   0.30  Midfielder      2010–11
 7     8   Steven Gerrard       92    504   0.18  Midfielder    1999–2000
 8     9     James Milner       87    607   0.14  Midfielder      2004–05
 9    10    David Beckham       80    265   0.30  Midfielder      1995–96

   Last assist
 0     2012–13
 1     2017–18
 2     2017–18
 3     2014–15
 4     2022–23
 5     2005–06
 6     2019–20
 7     2014–15
 8     2022–23
 9     2002–03  ,
    Rank             Player  Clean sheets  Games  Ratio First season  \
 0     1          Petr Čech           202    443   0.46      2004–05
 1     2        David James           169    572   0.30      1992–93
 2     3     Mark Schwarzer           151    514   0.29      1996–97
 3     4       David Seaman           141    344   0.41      1992–93
 4     5       David de Gea           140    402   0.35      2011–12
 5     6       Nigel Martyn           137    372   0.37      1992–93
 6     7         Pepe Reina           136    297   0.46      2005–06
 7     8  Edwin van der Sar           132    313   0.42      2001–02
 8     8         Tim Howard           132    399   0.33      2003–04
 9     8       Brad Friedel           132    450   0.29      1997–98

   Last season
 0     2018–19
 1     2009–10
 2     2014–15
 3     2003–04
 4     2022–23
 5     2005–06
 6     2019–20
 7     2010–11
 8     2015–16
 9     2013–14  ,
     Pos.                     Club  Seasons   Pld    W    D    L    GF    GA  \
 0      1        Manchester United       30  1152  703  257  192  2185  1066
 1      2                  Arsenal       30  1152  619  284  249  2017  1148
 2      3                  Chelsea       30  1152  618  284  250  1973  1125
 3      4                Liverpool       30  1152  609  282  261  2021  1147
 4      5        Tottenham Hotspur       30  1152  502  281  369  1745  1438
 5      6          Manchester City       25   962  473  210  279  1658  1068
 6      7                  Everton       30  1152  418  320  414  1491  1481
 7      8         Newcastle United       27  1034  382  264  388  1377  1417
 8      9              Aston Villa       27  1038  354  296  388  1265  1353
 9     10          West Ham United       26   996  335  253  408  1235  1429
 10    11              Southampton       23   886  274  241  371  1078  1282
 11    12         Blackburn Rovers       18   696  262  184  250   927   907
 12    13             Leeds United       14   544  216  141  187   745   706
 13    14           Leicester City       16   612  209  160  243   820   868
 14    15            Middlesbrough       15   574  165  169  240   648   794
 15    16                   Fulham       15   570  162  154  254   631   831
 16    17               Sunderland       16   608  153  159  296   612   904
 17    18         Bolton Wanderers       13   494  149  128  217   575   745
 18    19           Crystal Palace       13   502  145  129  228   547   726
 19    20     West Bromwich Albion       13   494  117  139  238   510   772
 20    21               Stoke City       10   380  116  109  155   398   525
 21    22            Coventry City        9   354   99  112  143   387   490
 22    23             Norwich City       10   392   99  105  188   414   669
 23    24      Sheffield Wednesday        8   316  101   89  126   409   453
 24    25             Wimbledon[h]        8   316   99   94  123   384   472
 25    26        Charlton Athletic        8   304   93   82  129   342   442
 26    27  Wolverhampton Wanderers        8   304   90   78  136   328   462
 27    28           Wigan Athletic        8   304   85   76  143   316   482
 28    29                  Burnley        8   304   83   76  145   300   455
 29    30             Swansea City        7   266   82   66  118   306   383
 30    31      Queens Park Rangers        7   278   81   65  132   339   431
 31    32          Birmingham City        7   266   73   82  111   273   360
 32    33               Portsmouth        7   266   79   65  122   292   380
 33    34                  Watford        8   304   73   66  165   310   518
 34    35             Derby County        7   266   68   70  128   271   420
 35    36        Nottingham Forest        5   198   60   59   79   229   287
 36    37             Ipswich Town        5   202   57   53   92   219   312
 37    38              Bournemouth        5   190   56   43   91   241   330
 38    39   Brighton & Hove Albion        5   190   48   65   77   190   258
 39    40         Sheffield United        5   198   53   50   95   187   270
 40    41                Hull City        5   190   41   48  101   181   323
 41    42                  Reading        3   114   32   23   59   136   186
 42    43          Oldham Athletic        2    84   22   23   39   105   142
 43    44             Cardiff City        2    76   17   13   46    66   143
 44    45            Bradford City        2    76   14   20   42    68   138
 45    46        Huddersfield Town        2    76   12   17   47    50   134
 46    47                Brentford        2    38   13    7   18    48    56
 47    48                Blackpool        1    38   10    9   19    55    78
 48    49                 Barnsley        1    38   10    5   23    37    82
 49    50             Swindon Town        1    42    5   15   22    47   100

       GD  ...  4th  5th  6th  7th    T4    T7      Debut  Since/Last App.  \
 0   1119  ...  1.0  1.0  3.0  1.0  25.0  30.0    1992–93       1992–93[a]
 1    869  ...  7.0  4.0  1.0  NaN  21.0  26.0    1992–93       1992–93[b]
 2    848  ...  4.0  2.0  4.0  NaN  19.0  25.0    1992–93       1992–93[c]
 3    874  ...  7.0  2.0  3.0  3.0  19.0  27.0    1992–93       1992–93[d]
 4    307  ...  4.0  5.0  2.0  2.0   7.0  16.0    1992–93       1992–93[e]
 5    590  ...  1.0  1.0  NaN  NaN  12.0  13.0    1992–93          2002–03
 6     10  ...  1.0  3.0  3.0  4.0   1.0  11.0    1992–93       1992–93[f]
 7    −40  ...  1.0  2.0  1.0  1.0   5.0   9.0    1993–94          2017–18
 8    −88  ...  1.0  1.0  6.0  1.0   2.0  10.0    1992–93          2019–20
 9   −194  ...  NaN  1.0  1.0  3.0   NaN   5.0    1993–94          2012–13
 10  −204  ...  NaN  NaN  1.0  1.0   NaN   2.0    1992–93          2012–13
 11    20  ...  1.0  NaN  3.0  2.0   3.0   8.0    1992–93          2011–12
 12    39  ...  2.0  4.0  NaN  NaN   3.0   7.0    1992–93          2020–21
 13   −48  ...  NaN  2.0  NaN  NaN   1.0   3.0    1994–95          2014–15
 14  −146  ...  NaN  NaN  NaN  1.0   NaN   1.0    1992–93          2016–17
 15  −200  ...  NaN  NaN  NaN  1.0   NaN   1.0    2001–02          2022–23
 16  −292  ...  NaN  NaN  NaN  2.0   NaN   2.0    1996–97          2016–17
 17  −170  ...  NaN  NaN  1.0  1.0   NaN   2.0    1995–96          2011–12
 18  −179  ...  NaN  NaN  NaN  NaN   NaN   NaN    1992–93          2013–14
 19  −262  ...  NaN  NaN  NaN  NaN   NaN   NaN    2002–03          2020–21
 20  −127  ...  NaN  NaN  NaN  NaN   NaN   NaN    2008–09          2017–18
 21  −103  ...  NaN  NaN  NaN  NaN   NaN   NaN    1992–93          2000–01
 22  −255  ...  NaN  NaN  NaN  NaN   1.0   1.0    1992–93          2021–22
 23   −44  ...  NaN  NaN  NaN  3.0   NaN   3.0    1992–93        1999–2000
 24   −88  ...  NaN  NaN  1.0  NaN   NaN   1.0    1992–93        1999–2000
 25  −100  ...  NaN  NaN  NaN  1.0   NaN   1.0    1998–99          2006–07
 26  −134  ...  NaN  NaN  NaN  2.0   NaN   2.0    2003–04          2018–19
 27  −166  ...  NaN  NaN  NaN  NaN   NaN   NaN    2005–06          2012–13
 28  −155  ...  NaN  NaN  NaN  1.0   NaN   1.0    2009–10          2016–17
 29   −77  ...  NaN  NaN  NaN  NaN   NaN   NaN    2011–12          2017–18
 30   −92  ...  NaN  1.0  NaN  NaN   NaN   1.0    1992–93          2014–15
 31   −87  ...  NaN  NaN  NaN  NaN   NaN   NaN    2002–03          2010–11
 32   −88  ...  NaN  NaN  NaN  NaN   NaN   NaN    2003–04          2009–10
 33  −208  ...  NaN  NaN  NaN  NaN   NaN   NaN  1999–2000          2021–22
 34  −149  ...  NaN  NaN  NaN  NaN   NaN   NaN    1996–97          2007–08
 35   −58  ...  NaN  NaN  NaN  NaN   1.0   1.0    1992–93          2022–23
 36   −93  ...  NaN  1.0  NaN  NaN   NaN   1.0    1992–93          2001–02
 37   −89  ...  NaN  NaN  NaN  NaN   NaN   NaN    2015–16          2022–23
 38   −68  ...  NaN  NaN  NaN  NaN   NaN   NaN    2017–18          2017–18
 39   −83  ...  NaN  NaN  NaN  NaN   NaN   NaN    1992–93          2020–21
 40  −142  ...  NaN  NaN  NaN  NaN   NaN   NaN    2008–09          2016–17
 41   −50  ...  NaN  NaN  NaN  NaN   NaN   NaN    2006–07          2012–13
 42   −37  ...  NaN  NaN  NaN  NaN   NaN   NaN    1992–93          1993–94
 43   −77  ...  NaN  NaN  NaN  NaN   NaN   NaN    2013–14          2018–19
 44   −70  ...  NaN  NaN  NaN  NaN   NaN   NaN  1999–2000          2000–01
 45   −84  ...  NaN  NaN  NaN  NaN   NaN   NaN    2017–18          2018–19
 46    −8  ...  NaN  NaN  NaN  NaN   NaN   NaN    2021–22          2021–22
 47   −23  ...  NaN  NaN  NaN  NaN   NaN   NaN    2010–11          2010–11
 48   −45  ...  NaN  NaN  NaN  NaN   NaN   NaN    1997–98          1997–98
 49   −53  ...  NaN  NaN  NaN  NaN   NaN   NaN    1993–94          1993–94

     Relegated  BestPos.
 0         NaN         1
 1         NaN         1
 2         NaN         1
 3         NaN         1
 4         NaN         2
 5         2.0         1
 6         NaN         4
 7         2.0         2
 8         1.0         2
 9         2.0         5
 10        1.0         6
 11        2.0         1
 12        1.0         3
 13        3.0         1
 14        4.0         7
 15        3.0         7
 16        4.0         7
 17        3.0         6
 18        4.0        10
 19        5.0         8
 20        1.0         9
 21        1.0        11
 22        6.0         3
 23        1.0         7
 24        1.0         6
 25        2.0         7
 26        2.0         7
 27        1.0        10
 28        3.0         7
 29        1.0         8
 30        3.0         5
 31        3.0         9
 32        1.0         8
 33        4.0        11
 34        2.0         8
 35        3.0         3
 36        2.0         5
 37        1.0         9
 38        NaN         9
 39        3.0         9
 40        3.0        16
 41        2.0         8
 42        1.0        19
 43        2.0        18
 44        1.0        17
 45        1.0        16
 46        NaN        13
 47        1.0        19
 48        1.0        19
 49        1.0        22

 [50 rows x 24 columns],
     0                               1
 0 NaN    2022–23 Premier League teams
 1 NaN  2022–23 EFL Championship teams
 2 NaN    2022–23 EFL League One teams
 3 NaN    2022–23 EFL League Two teams
 4 NaN   2022–23 National League teams
 5 NaN                   Defunct teams,
   .mw-parser-output .navbar{display:inline;font-size:88%;font-weight:normal}.mw-parser-output .navbar-collapse{float:left;text-align:left}.mw-parser-output .navbar-boxtext{word-spacing:0}.mw-parser-output .navbar ul{display:inline-block;white-space:nowrap;line-height:inherit}.mw-parser-output .navbar-brackets::before{margin-right:-0.125em;content:"[ "}.mw-parser-output .navbar-brackets::after{margin-left:-0.125em;content:" ]"}.mw-parser-output .navbar li{word-spacing:-0.125em}.mw-parser-output .navbar a>span,.mw-parser-output .navbar a>abbr{text-decoration:inherit}.mw-parser-output .navbar-mini abbr{font-variant:small-caps;border-bottom:none;text-decoration:none;cursor:inherit}.mw-parser-output .navbar-ct-full{font-size:114%;margin:0 7em}.mw-parser-output .navbar-ct-mini{font-size:114%;margin:0 4em}vtePremier League  \
 0                                            Seasons
 1                                              Clubs
 2                                            2022–23
 3                                             Former
 4                                        Competition
 5                              Statistics and awards
 6                                           Finances
 7                            Associated competitions
 8                                           Category

   .mw-parser-output .navbar{display:inline;font-size:88%;font-weight:normal}.mw-parser-output .navbar-collapse{float:left;text-align:left}.mw-parser-output .navbar-boxtext{word-spacing:0}.mw-parser-output .navbar ul{display:inline-block;white-space:nowrap;line-height:inherit}.mw-parser-output .navbar-brackets::before{margin-right:-0.125em;content:"[ "}.mw-parser-output .navbar-brackets::after{margin-left:-0.125em;content:" ]"}.mw-parser-output .navbar li{word-spacing:-0.125em}.mw-parser-output .navbar a>span,.mw-parser-output .navbar a>abbr{text-decoration:inherit}.mw-parser-output .navbar-mini abbr{font-variant:small-caps;border-bottom:none;text-decoration:none;cursor:inherit}.mw-parser-output .navbar-ct-full{font-size:114%;margin:0 7em}.mw-parser-output .navbar-ct-mini{font-size:114%;margin:0 4em}vtePremier League.1
 0  1992–93 1993–94 1994–95 1995–96 1996–97 1997–9...
 1  2022–23 Arsenal Aston Villa Bournemouth Brentf...
 2  Arsenal Aston Villa Bournemouth Brentford Brig...
 3  Barnsley Birmingham City Blackburn Rovers Blac...
 4  Teams winners performance record Players forei...
 5  Records All-time table Hat-tricks Highest scor...
 6  Richest clubs: Deloitte list Forbes' list Team...
 7  Asia Trophy FA Community Shield FA Cup EFL Cup...
 8                                           Category                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           ,
          0                                                  1
 0  2022–23  Arsenal Aston Villa Bournemouth Brentford Brig...
 1   Former  Barnsley Birmingham City Blackburn Rovers Blac...]

In [4]:
scraper[0]

   Rank           Player  Games    Position First season Last season
0     1     Gareth Barry    653  Midfielder      1997–98     2017–18
1     2       Ryan Giggs    632  Midfielder      1992–93     2013–14
2     3    Frank Lampard    609  Midfielder      1995–96     2014–15
3     4     James Milner    607  Midfielder      2002–03     2022–23
4     5      David James    572  Goalkeeper      1992–93     2009–10
5     6       Gary Speed    535  Midfielder      1992–93     2007–08
6     7     Emile Heskey    516     Forward      1994–95     2011–12
7     8   Mark Schwarzer    514  Goalkeeper      1996–97     2014–15
8     9  Jamie Carragher    508    Defender      1996–97     2012–13
9    10     Phil Neville    505    Defender      1994–95     2012–13

In [5]:
df = scraper[0]

df.to_csv('premier_league.csv', index= False)
df_scraped_file = pd.read_csv('premier_league.csv')

df_scraped_file

   Rank           Player  Games    Position First season Last season
0     1     Gareth Barry    653  Midfielder      1997–98     2017–18
1     2       Ryan Giggs    632  Midfielder      1992–93     2013–14
2     3    Frank Lampard    609  Midfielder      1995–96     2014–15
3     4     James Milner    607  Midfielder      2002–03     2022–23
4     5      David James    572  Goalkeeper      1992–93     2009–10
5     6       Gary Speed    535  Midfielder      1992–93     2007–08
6     7     Emile Heskey    516     Forward      1994–95     2011–12
7     8   Mark Schwarzer    514  Goalkeeper      1996–97     2014–15
8     9  Jamie Carragher    508    Defender      1996–97     2012–13
9    10     Phil Neville    505    Defender      1994–95     2012–13